apiVersion: v1
kind: Service
metadata:
  name: corda-bank-service
spec:
  type: LoadBalancer
  selector:
    app: corda-bank-node
  ports:
    - protocol: TCP
      name: p2p
      port: 10005
      nodePort: 10005
    - protocol: TCP
      name: rpc
      port: 10006
      nodePort: 10006
    - protocol: TCP
      name: adminrpc
      port: 10046
      nodePort: 10046
  selector:
    app: corda-bank-node
    version: v1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: corda-bank-deployment
  labels:
    app: corda-bank-node
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corda-bank-node
      version: v1
  template:
    metadata:
      labels:
        app: corda-bank-node
        version: v1
    spec:
      containers:
        - name: corda-bank
          image: ehkdpoc/corda-bank:v0.1
          ports:
            - containerPort: 10005
            - containerPort: 10006
            - containerPort: 10046