apiVersion: v1
kind: Service
metadata:
  name: corda-notary-service
spec:
  type: LoadBalancer
  selector:
    app: corda-notary-node
  ports:
    - protocol: TCP
      name: p2p
      port: 10002
      nodePort: 10002
    - protocol: TCP
      name: rpc
      port: 10003
      nodePort: 10003
    - protocol: TCP
      name: adminrpc
      port: 10043
      nodePort: 10043
  selector:
    app: corda-notary-node
    version: v1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: corda-notary-deployment
  labels:
    app: corda-notary-node
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corda-notary-node
      version: v1
  template:
    metadata:
      labels:
        app: corda-notary-node
        version: v1
    spec:
      containers:
        - name: corda-notary
          image: ehkdpoc/corda-notary:v0.1
          ports:
            - containerPort: 10002
            - containerPort: 10003
            - containerPort: 10043