FROM corda/community:4.9-zulu-openjdk8

COPY certificates/   /opt/corda/certificates
COPY config/   /etc/corda
COPY cordapps/  /opt/corda/cordapps
COPY drivers/   /opt/corda/drivers
COPY node-infos/ /opt/corda/additional-node-infos
COPY network-parameters /opt/corda/
